// Generated by CoffeeScript 1.7.1
var app;

app = angular.module("bhajans", ["ngTouch", "ngAnimate"]);

app.config(function($sceProvider) {
  return $sceProvider.enabled(false);
});

app.filter("highlight", function() {
  return function(text, search, caseSensitive) {
    if (text && (search || angular.isNumber(search))) {
      text = text.toString();
      search = search.toString();
      if (caseSensitive) {
        return text.split(search).join("<span class=\"ui-match\">" + search + "</span>");
      } else {
        return text.replace(new RegExp(search, "gi"), "<span class=\"ui-match\">$&</span>");
      }
    } else {
      return text;
    }
  };
});

app.controller("BhajanSearchCtrl", [
  "$scope", "$http", function($scope, $http) {
    $http.get("bhajan-index.json").success(function(data) {
      $scope.bhajans = data;
      storage.bhajans = data;
    });
  }
]);
